package com.cho.basic.연관관계매핑;

import com.cho.basic.repository.BookRepository;
import com.cho.basic.repository.LibraryRepository;
import com.cho.basic.repository.MemberRepository;
import com.cho.basic.vo.연관관계매핑.Book;
import com.cho.basic.vo.연관관계매핑.Library;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.junit.jupiter.SpringExtension;

//@Transactional
//@SpringBootTest
//@Rollback(value = false)
@ExtendWith(SpringExtension.class)
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
public class 연관관계_테스트 {

    @Autowired
    private MemberRepository memberRepository;

    @Autowired
    private BookRepository bookRepository;

    @Autowired
    private LibraryRepository libraryRepository;

    /**
     * init database with hibernate
     *
     * Hibernate:
     *
     *     create table book (
     *        id bigint generated by default as identity,
     *         name varchar(255),
     *         title varchar(255),
     *         library_id bigint,
     *         primary key (id)
     *     )
     * Hibernate:
     *
     *     create table library (
     *        id bigint generated by default as identity,
     *         library_name varchar(255),
     *         primary key (id)
     *     )
     * Hibernate:
     *
     *     alter table member
     *        add column intro varchar(500)
     * Hibernate:
     *
     *     alter table member
     *        add column login_type varchar(255)
     * Hibernate:
     *
     *     alter table member
     *        add column mypage_id bigint
     * Hibernate:
     *
     *     create table my_page (
     *        id bigint not null,
     *         primary key (id)
     *     )
     * Hibernate:
     *
     *     alter table book
     *        add constraint FKaojxagnfmppd09k35kye5eph5
     *        foreign key (library_id)
     *        references library
     * Hibernate:
     *
     *     alter table member
     *        add constraint FK5d6wtnd7apxua1347jsvsc93a
     *        foreign key (mypage_id)
     *        references my_page
     */

    @Test
    public void LibrarySave() throws Exception
    {
        //given
        Book book1 = new Book();
        book1.setName("THIS IS BOOK1");

        Book book2 = new Book();
        book2.setName("THIS IS BOOK2");

        Library library = new Library();
        library.setLibraryName("ABC LIBRARY");

        //when
        System.out.println("================QUERY START================");
        bookRepository.save(book1);
        bookRepository.save(book2);
        System.out.println("================QUERY END================\n");

        /**
         * console.log
         *
         * ================QUERY START================
         * Hibernate:
         *     insert
         *     into
         *         book
         *         (id, library_id, name, title)
         *     values
         *         (null, ?, ?, ?)
         * Hibernate:
         *     insert
         *     into
         *         book
         *         (id, library_id, name, title)
         *     values
         *         (null, ?, ?, ?)
         * ================QUERY END================
         */

        library.addBook(book1);
        library.addBook(book2);
        System.out.println("================QUERY START================");
        libraryRepository.save(library);
        System.out.println("================QUERY END================\n");

        /**
         * console.log
         *
         * ================QUERY START================
         * Hibernate:
         *     insert
         *     into
         *         library
         *         (id, library_name)
         *     values
         *         (null, ?)
         * ================QUERY END================
         */
    }
}

