version: "3"

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq-stream
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    environment:
      RABBITMQ_ERLANG_COOKIE: "RabbitMQ-My-Cookies"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
#    volumes:
#      - ./messageQueue/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
#      - ./messageQueue/my_definition.json:/etc/rabbitmq/my_definition.json
