spring:
  profiles:
    active: local

# Local 환경
---
spring:
  profiles: local

  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    ROOT: info #debug
