version: '3.5'
services:
  database:
    build:
      context: ./postgres
      dockerfile: db.Dockerfile
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - ./var/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myblog